# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10dac688e0389bd44ff865a12e4272c39d3fa75d9c46fadc692dca9de9e5b482b90be0ab77866df6f156d9d123a08e2d52a0231cd7dcc6ca04c080cc47471838

test:
  secret_key_base: b4f18d9ff8ac3eb8eb38cd7302c0788e066707ba6ab543c04b63c0459d4f5175729d25e605e41b7b3c61b58f8f29a8087b5d0ec73a8cb80d6ff812a0cc2103f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
